# Generated by Django 3.2.16 on 2022-11-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(null=True)),
                ('adress', models.CharField(max_length=500, null=True)),
                ('salary', models.IntegerField(null=True)),
                ('join_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
